// <auto-generated />
using System;
using Bocasay.Data.SqlServer.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bocasay.Data.SqlServer.Migrations
{
    [DbContext(typeof(CommonDBContext))]
    [Migration("20211120181518_SeedingDataV4")]
    partial class SeedingDataV4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.Role", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleCategory")
                        .HasColumnType("int");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = new Guid("6f8fad5b-d9cb-469f-a165-708677289506"),
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Administrator",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleCategory = 0,
                            RoleCode = "Admin"
                        },
                        new
                        {
                            ID = new Guid("6a4fad5b-d9cb-469f-a165-708677289506"),
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Viewer",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleCategory = 1,
                            RoleCode = "Viewer"
                        });
                });

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = new Guid("6f8fad5b-d9cb-469f-a165-70867728950e"),
                            Address = "1A - HHT st",
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Davidtommy.bocasy.com",
                            FullName = "David Tommy",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = new Guid("6f8fad5b-d9cb-469f-a165-70867728ab56"),
                            Address = "13B - HHT st",
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Sakcaphonel.bocasy.com",
                            FullName = "Sakca Phonel",
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.UserRoleMap", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserID");

                    b.ToTable("UserRoleMaps");

                    b.HasData(
                        new
                        {
                            ID = new Guid("688fad5b-d9cb-469f-a165-708677289506"),
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleID = new Guid("6f8fad5b-d9cb-469f-a165-708677289506"),
                            UserID = new Guid("6f8fad5b-d9cb-469f-a165-70867728950e")
                        },
                        new
                        {
                            ID = new Guid("600fad5b-d9cb-469f-a165-708677289506"),
                            CreatedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            ModifiedDate = new DateTime(2021, 11, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RoleID = new Guid("6a4fad5b-d9cb-469f-a165-708677289506"),
                            UserID = new Guid("6f8fad5b-d9cb-469f-a165-70867728ab56")
                        });
                });

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.UserRoleMap", b =>
                {
                    b.HasOne("Bocasay.Data.SqlServer.Etities.Role", "Role")
                        .WithMany("UserRoleMaps")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bocasay.Data.SqlServer.Etities.User", "User")
                        .WithMany("UserRoleMaps")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.Role", b =>
                {
                    b.Navigation("UserRoleMaps");
                });

            modelBuilder.Entity("Bocasay.Data.SqlServer.Etities.User", b =>
                {
                    b.Navigation("UserRoleMaps");
                });
#pragma warning restore 612, 618
        }
    }
}
